
-- Tạo user quoctay với quyền admin
CREATE ROLE quoctay WITH LOGIN SUPERUSER PASSWORD 'password';
-- DROP SCHEMA public;

CREATE SCHEMA public AUTHORIZATION postgres;

-- DROP TYPE public."appointmentstatus";

CREATE TYPE public."appointmentstatus" AS ENUM (
	'CANCELLED',
	'COMPLETED',
	'CONFIRMED',
	'PENDING');

-- DROP TYPE public."examinationtype";

CREATE TYPE public."examinationtype" AS ENUM (
	'REGULAR',
	'VIP');

-- DROP TYPE public."periodenum";

CREATE TYPE public."periodenum" AS ENUM (
	'AFTERNOON',
	'LUNCH',
	'MORNING');

-- DROP SEQUENCE public.appointment_history_id_seq;

CREATE SEQUENCE public.appointment_history_id_seq
	INCREMENT BY 1
	MINVALUE 1
	MAXVALUE 9223372036854775807
	START 1
	CACHE 1
	NO CYCLE;

-- Permissions

ALTER SEQUENCE public.appointment_history_id_seq OWNER TO quoctay;
GRANT ALL ON SEQUENCE public.appointment_history_id_seq TO quoctay;

-- DROP SEQUENCE public.appointments_id_seq;

CREATE SEQUENCE public.appointments_id_seq
	INCREMENT BY 1
	MINVALUE 1
	MAXVALUE 9223372036854775807
	START 1
	CACHE 1
	NO CYCLE;

-- Permissions

ALTER SEQUENCE public.appointments_id_seq OWNER TO quoctay;
GRANT ALL ON SEQUENCE public.appointments_id_seq TO quoctay;

-- DROP SEQUENCE public.doctor_schedule_id_seq;

CREATE SEQUENCE public.doctor_schedule_id_seq
	INCREMENT BY 1
	MINVALUE 1
	MAXVALUE 9223372036854775807
	START 1
	CACHE 1
	NO CYCLE;

-- Permissions

ALTER SEQUENCE public.doctor_schedule_id_seq OWNER TO quoctay;
GRANT ALL ON SEQUENCE public.doctor_schedule_id_seq TO quoctay;

-- DROP SEQUENCE public.doctors_id_seq;

CREATE SEQUENCE public.doctors_id_seq
	INCREMENT BY 1
	MINVALUE 1
	MAXVALUE 9223372036854775807
	START 1
	CACHE 1
	NO CYCLE;

-- Permissions

ALTER SEQUENCE public.doctors_id_seq OWNER TO quoctay;
GRANT ALL ON SEQUENCE public.doctors_id_seq TO quoctay;

-- DROP SEQUENCE public.patients_id_seq;

CREATE SEQUENCE public.patients_id_seq
	INCREMENT BY 1
	MINVALUE 1
	MAXVALUE 9223372036854775807
	START 1
	CACHE 1
	NO CYCLE;

-- Permissions

ALTER SEQUENCE public.patients_id_seq OWNER TO quoctay;
GRANT ALL ON SEQUENCE public.patients_id_seq TO quoctay;

-- DROP SEQUENCE public.specialties_id_seq;

CREATE SEQUENCE public.specialties_id_seq
	INCREMENT BY 1
	MINVALUE 1
	MAXVALUE 9223372036854775807
	START 1
	CACHE 1
	NO CYCLE;

-- Permissions

ALTER SEQUENCE public.specialties_id_seq OWNER TO quoctay;
GRANT ALL ON SEQUENCE public.specialties_id_seq TO quoctay;
-- public.appointment_history definition

-- Drop table

-- DROP TABLE public.appointment_history;

CREATE TABLE public.appointment_history (
	id int8 NOT NULL GENERATED BY DEFAULT AS IDENTITY,
	appointment_id int8 NOT NULL,
	changed_at timestamp(6) NOT NULL,
	new_status varchar(255) NOT NULL,
	note varchar(255) NULL,
	old_status varchar(255) NULL,
	CONSTRAINT appointment_history_new_status_check CHECK (((new_status)::text = ANY ((ARRAY['PENDING'::character varying, 'CONFIRMED'::character varying, 'COMPLETED'::character varying, 'CANCELLED'::character varying])::text[]))),
	CONSTRAINT appointment_history_old_status_check CHECK (((old_status)::text = ANY ((ARRAY['PENDING'::character varying, 'CONFIRMED'::character varying, 'COMPLETED'::character varying, 'CANCELLED'::character varying])::text[]))),
	CONSTRAINT appointment_history_pkey PRIMARY KEY (id)
);

-- Permissions

ALTER TABLE public.appointment_history OWNER TO quoctay;
GRANT ALL ON TABLE public.appointment_history TO quoctay;


-- public.appointments definition

-- Drop table

-- DROP TABLE public.appointments;

CREATE TABLE public.appointments (
	id int8 NOT NULL GENERATED BY DEFAULT AS IDENTITY,
	created_at timestamp(6) NULL,
	created_by varchar(255) NULL,
	updated_at timestamp(6) NULL,
	updated_by varchar(255) NULL,
	appointment_date date NOT NULL,
	doctor_id int8 NOT NULL,
	doctor_name varchar(255) NULL,
	end_hour time(6) NULL,
	examination_type varchar(255) NOT NULL,
	patient_id int8 NOT NULL,
	patient_name varchar(255) NULL,
	"period" varchar(255) NOT NULL,
	specialty_id int8 NULL,
	specialty_name varchar(255) NULL,
	start_hour time(6) NULL,
	status varchar(255) NOT NULL,
	symptoms text NULL,
	CONSTRAINT appointments_examination_type_check CHECK (((examination_type)::text = ANY ((ARRAY['REGULAR'::character varying, 'VIP'::character varying])::text[]))),
	CONSTRAINT appointments_period_check CHECK (((period)::text = ANY ((ARRAY['MORNING'::character varying, 'LUNCH'::character varying, 'AFTERNOON'::character varying])::text[]))),
	CONSTRAINT appointments_pkey PRIMARY KEY (id),
	CONSTRAINT appointments_status_check CHECK (((status)::text = ANY ((ARRAY['PENDING'::character varying, 'CONFIRMED'::character varying, 'COMPLETED'::character varying, 'CANCELLED'::character varying])::text[])))
);

-- Permissions

ALTER TABLE public.appointments OWNER TO quoctay;
GRANT ALL ON TABLE public.appointments TO quoctay;


-- public.doctor_schedule definition

-- Drop table

-- DROP TABLE public.doctor_schedule;

CREATE TABLE public.doctor_schedule (
	id int8 NOT NULL GENERATED BY DEFAULT AS IDENTITY,
	created_at timestamp(6) NULL,
	created_by varchar(255) NULL,
	updated_at timestamp(6) NULL,
	updated_by varchar(255) NULL,
	available bool NOT NULL,
	"date" date NOT NULL,
	doctor_id int8 NOT NULL,
	end_hour time(6) NULL,
	"period" varchar(255) NULL,
	start_hour time(6) NULL,
	CONSTRAINT doctor_schedule_period_check CHECK (((period)::text = ANY ((ARRAY['MORNING'::character varying, 'LUNCH'::character varying, 'AFTERNOON'::character varying])::text[]))),
	CONSTRAINT doctor_schedule_pkey PRIMARY KEY (id)
);

-- Permissions

ALTER TABLE public.doctor_schedule OWNER TO quoctay;
GRANT ALL ON TABLE public.doctor_schedule TO quoctay;


-- public.patients definition

-- Drop table

-- DROP TABLE public.patients;

CREATE TABLE public.patients (
	id int8 NOT NULL GENERATED BY DEFAULT AS IDENTITY,
	created_at timestamp(6) NULL,
	created_by varchar(255) NULL,
	updated_at timestamp(6) NULL,
	updated_by varchar(255) NULL,
	customer_id int8 NOT NULL,
	district varchar(255) NOT NULL,
	dob date NOT NULL,
	full_name varchar(255) NOT NULL,
	gender int2 NOT NULL,
	nationality varchar(255) NOT NULL,
	phone varchar(255) NULL,
	province varchar(255) NOT NULL,
	street varchar(255) NOT NULL,
	ward varchar(255) NOT NULL,
	CONSTRAINT patients_gender_check CHECK (((gender >= 0) AND (gender <= 1))),
	CONSTRAINT patients_pkey PRIMARY KEY (id)
);

-- Permissions

ALTER TABLE public.patients OWNER TO quoctay;
GRANT ALL ON TABLE public.patients TO quoctay;


-- public.specialties definition

-- Drop table

-- DROP TABLE public.specialties;

CREATE TABLE public.specialties (
	id int8 NOT NULL GENERATED BY DEFAULT AS IDENTITY,
	created_at timestamp(6) NULL,
	created_by varchar(255) NULL,
	updated_at timestamp(6) NULL,
	updated_by varchar(255) NULL,
	code varchar(255) NULL,
	"name" varchar(255) NULL,
	CONSTRAINT specialties_pkey PRIMARY KEY (id),
	CONSTRAINT ukbhb8s9o5hv30lkbidtod9cixc UNIQUE (name)
);

-- Permissions

ALTER TABLE public.specialties OWNER TO quoctay;
GRANT ALL ON TABLE public.specialties TO quoctay;


-- public.doctors definition

-- Drop table

-- DROP TABLE public.doctors;

CREATE TABLE public.doctors (
	id int8 NOT NULL GENERATED BY DEFAULT AS IDENTITY,
	created_at timestamp(6) NULL,
	created_by varchar(255) NULL,
	updated_at timestamp(6) NULL,
	updated_by varchar(255) NULL,
	full_name varchar(255) NULL,
	specialty_id int8 NULL,
	CONSTRAINT doctors_pkey PRIMARY KEY (id),
	CONSTRAINT fkb4ymcpidvwfn4kybv4adfvxcm FOREIGN KEY (specialty_id) REFERENCES public.specialties(id)
);

-- Permissions

ALTER TABLE public.doctors OWNER TO quoctay;
GRANT ALL ON TABLE public.doctors TO quoctay;




-- Permissions

GRANT ALL ON SCHEMA public TO postgres;
