spring:
  config:
    activate:
      on-profile: prod
  devtools:
    add-properties: false
  datasource:
    url: ${POSTGRES_URL:jdbc:postgresql://dpg-cvuip395pdvs73c4mee0-a.oregon-postgres.render.com/appointment_3xa6}
    username: ${POSTGRES_USER:appointment_3xa6_user}
    password: ${POSTGRES_PASSWORD:ohXwD670kj8RKm6Q9DTgq4kZ4OOOzaV9}
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
    show-sql: false
    hibernate:
      ddl-auto: none

# API document setting
# springdoc:
#   api-docs:
#     enabled: false
#   swagger-ui:
#     enabled: false

springdoc:
  api-docs:
    enabled: true
  swagger-ui:
    enabled: true

openapi:
  service:
    api-docs: appointment-service
    server: http://localhost:4953/appointment  # Không cần bắt buộc
    title: Appointment service
    version: 1.0.0
